CREATE TABLE PASSENGER
(
    PASSENGER_ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME      VARCHAR(100) NOT NULL,
    EMAIL     VARCHAR(100) NOT NULL
);

INSERT INTO PASSENGER (NAME, EMAIL)
VALUES ('JOHN DOE', 'JOHN.DOE@EXAMPLE.COM'),
       ('JANE SMITH', 'JANE.SMITH@EXAMPLE.COM'),
       ('EMILY JOHNSON', 'EMILY.JOHNSON@EXAMPLE.COM');